# Generated by Django 6.0.2 on 2026-02-15 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the book title', max_length=200)),
                ('author', models.CharField(help_text="Enter the author's name", max_length=100)),
                ('isbn', models.CharField(help_text='13 Character ISBN number', max_length=13, unique=True)),
                ('publisher', models.CharField(blank=True, help_text='Publisher name (optional)', max_length=100)),
                ('publication_year', models.IntegerField(help_text='Year of publication', validators=[django.core.validators.MinValueValidator(1000)])),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('science', 'Science'), ('history', 'History'), ('biography', 'Biography'), ('children', 'Children'), ('reference', 'Reference')], default='fiction', max_length=50)),
                ('total_copies', models.IntegerField(default=1, help_text='Total number of copies', validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.IntegerField(default=1, help_text='Number of copies available for borrowing', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Brief description of the book')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
    ]
